source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'uye' do
    #网络请求
    pod 'Alamofire', '~> 4.5.1'
    #键盘监控
    pod 'IQKeyboardManagerSwift', '5.0.0'
    #约束条件
    pod 'SnapKit', '~> 4.0.0'
    #Model映射
    pod 'HandyJSON', '~> 4.0.0-beta.1'
    pod 'Moya', '~> 9.0.0'
    
    pod 'BaiduMapKit', '~> 3.4.0'
    #图片缓存
    pod 'Kingfisher', '~> 4.0.1'
    #下拉刷新
    pod 'MJRefresh', '~> 3.1.12'
    #钥匙串
    #pod 'SwiftKeychainWrapper', '~> 3.0.1'
    pod 'FCUUID', '~> 1.3.1'
    #首页轮播图
    pod 'LLCycleScrollView', '~> 1.4.1'
end
