source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'uye' do
    pod 'Alamofire', '~> 4.4.0'
    pod 'IQKeyboardManagerSwift'
    pod 'SnapKit', '~> 3.2.0'
    pod 'HandyJSON', '~> 1.7.2'

end
