source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'uye' do
    pod 'Alamofire', '~> 4.5.1'
    pod 'IQKeyboardManagerSwift', '5.0.0'
    pod 'SnapKit', '~> 4.0.0'
    pod 'HandyJSON', '~> 4.0.0-beta.1'
    pod 'Moya', '~> 9.0.0'
end
